### ISSUE TITLE
How to add a favicon?

### ISSUE THREAD

**Issue by omeyrick** [klugjo/klugjo.github.io#1]
Hi there - great theme. Is there a way to add a favicon to it? Thanks.

**Comment by klugjo** [comment]
Which theme are you talking about ? You have raised this issue on my blog static hosting space

**Comment by omeyrick** [comment]
Nuts - sorry. The phantom theme.

**Comment by klugjo** [comment]
you should add it to the `head.ejs` file as you would for any other website, inside the `<head />`

https://github.com/klugjo/hexo-theme-phantom/blob/master/layout/_partial/head.ejs

For my blog, I am using http://www.favicon-generator.org/ to generate the actual icon and the html, then you can just copy paste it

**Comment by omeyrick** [comment]
Great, thanks!
